
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zak
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Help");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 131, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(5, 5, 5)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 JOptionPane frame;
        frame = new JOptionPane("");
 JOptionPane.showMessageDialog(frame, "Contact I.T.");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 String password;
        password = jPasswordField1.getText();
  String username;
        username = jTextField1.getText();
        if(password.contains("TotallyNotPassword")&&username.contains("Admin")){
            jPasswordField1.setText("");
            jTextField1.setText("");
            JOptionPane passcheck = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck, "Welcome Admin");
             Admin frame1=new Admin();
            frame1.setVisible(true);
            dispose();
            
        }
        else if(password.contains("Password")&&username.contains("Secretary")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Secretary");
            SecView frame1=new SecView();
            frame1.setVisible(true);
            dispose();
        }
           else if(password.contains("0X60I7sjt")&&username.contains("D.Smith")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Smith");
        }
           else if(password.contains("dADFfbVHnN")&&username.contains("C.Brown")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Brown");
           }
           else if(password.contains("IpwYUg7uTw")&&username.contains("K.Jones")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Jones");
           }
           else if(password.contains("SrgPtx5Y9z")&&username.contains("R.Kalt")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Kalt");
           }
           else if(password.contains("jYKUt71Ir0")&&username.contains("H.Denne")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Denne");
           }
           else if(password.contains("a0GHCQhLkY")&&username.contains("G.Throop")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Throop");
           }
           else if(password.contains("gVYK8Ku8iE")&&username.contains("S.Whitney")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Whitney");
           }
           else if(password.contains("IF1rQU61Hw")&&username.contains("H.Henebury")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Henebury");
           }
           else if(password.contains("egrnc2BcFV")&&username.contains("K.Cormier")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Cormier");
           }
           else if(password.contains("x4PoREtOt8")&&username.contains("W.Rhode")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Rhode");
           }
           else if(password.contains("j7HussNxV5")&&username.contains("J.Sussman")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Sussman");
           }
           else if(password.contains("FCzSv6AEff")&&username.contains("B.Chua")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Chua");
           }
           else if(password.contains("7d725XZoSr")&&username.contains("B.Svedrofsky")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Svedrofsky");
           }
           else if(password.contains("mjKkSfLZxm")&&username.contains("A.Berdichevsky")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Berdichevsky");
           }
           else if(password.contains("y3c6XzvwUb")&&username.contains("A.Vancil")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Vancil");
           }
           else if(password.contains("01vqzBzkjh")&&username.contains("K.Fargo")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Fargo");
           }
           else if(password.contains("sP8woBYWKB")&&username.contains("S.Carpenter")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Carpenter");
           }
           else if(password.contains("a0FCSVI9sr")&&username.contains("W.Dunlop")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Dunlop");
           }
           else if(password.contains("Mfu0Ibjv8J")&&username.contains("S.Colen")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Colen");
           }
           else if(password.contains("JyeHfB8swP")&&username.contains("M.Dermody")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Dermody");
           }
           else if(password.contains("WenIYCL6qP")&&username.contains("M.Dai")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Dai");
           }
           else if(password.contains("Aq8Kv6vMu7")&&username.contains("C.Serageldin")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Serageldin");
           }
           else if(password.contains("LPIQZSSwMK")&&username.contains("D.Morgan")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Morgan");
           }
           else if(password.contains("9fRL1FnatO")&&username.contains("C.Chiodi")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Chiodi");
           }
           else if(password.contains("QPLJt3bPuU")&&username.contains("B.Broom")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Broom");
           }
           else if(password.contains("kPQDwsBaHr")&&username.contains("C.Yokoe")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Yokoe");
           }
           else if(password.contains("XZDdGhuGYl")&&username.contains("L.Everette")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Everette");
           }
           else if(password.contains("1XQq8rWxQX")&&username.contains("T.Ronen")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Ronen");
           }
           else if(password.contains("Esk6sKupPJ")&&username.contains("J.Dowsland")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Dowsland");
           }
           else if(password.contains("CbkH57Mbqz")&&username.contains("H.Dostoievski")){
            JOptionPane passcheck1 = new JOptionPane("");
            JOptionPane.showMessageDialog(passcheck1, "Welcome Dr.Dostoievski");
           }
        else {
            JOptionPane check = new JOptionPane("");
            JOptionPane.showMessageDialog(check, "Invalid Combination");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
       
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
     
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
